stages:    
    - test

pytest:
  stage: test

  before_script:
    - yum -y install python3-pip
    - pip --version
    - pip install -r requirements.txt
    
  script: 
    - cd python
    - pytest -v .